apiVersion: v1
kind: ConfigMap
metadata:
  name: togglemaster-config
data:
  AUTH_SERVICE_URL: http://auth-service:8001
  FLAG_SERVICE_URL: http://flag-service:8002
  TARGETING_SERVICE_URL: http://targeting-service:8003
  AUTH_DB_HOST: replace-with-auth-postgresql-private-ip
  AUTH_DB_NAME: auth_db
  AUTH_DB_USER: auth_app
  FLAG_DB_HOST: replace-with-flag-postgresql-private-ip
  FLAG_DB_NAME: flags_db
  FLAG_DB_USER: flags_app
  TARGETING_DB_HOST: replace-with-targeting-postgresql-private-ip
  TARGETING_DB_NAME: targeting_db
  TARGETING_DB_USER: targeting_app
  DB_PORT: "5432"
  DB_SSLMODE: require
  REDIS_URL: rediss://replace-with-redis-private-fqdn:6379
  OCI_AUTH_MODE: workload_identity
  OCI_REGION: replace-with-oci-region
  OCI_QUEUE_OCID: replace-with-queue-ocid
  OCI_QUEUE_MESSAGES_ENDPOINT: replace-with-queue-messages-endpoint
  OCI_NOSQL_TABLE: replace-with-nosql-table-ocid
  OCI_COMPARTMENT_OCID: replace-with-compartment-ocid
  ANALYTICS_WORKER_ENABLED: "false"
