apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: auth-service
  ports:
    - name: http
      port: 8001
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: flag-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: flag-service
  ports:
    - name: http
      port: 8002
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: targeting-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: targeting-service
  ports:
    - name: http
      port: 8003
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: evaluation-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: evaluation-service
  ports:
    - name: http
      port: 8004
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: analytics-service
  ports:
    - name: http
      port: 8005
      targetPort: http
