apiVersion: apps/v1
kind: Deployment
metadata:
  name: flag-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: flag-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flag-service
    spec:
      serviceAccountName: flag-service
      imagePullSecrets:
        - name: ocir-pull-secret
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: flag-service
          image: togglemaster/flag-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8002
          env:
            - name: PORT
              value: "8002"
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: togglemaster-config
                  key: AUTH_SERVICE_URL
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: togglemaster-config
                  key: FLAG_DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: togglemaster-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: togglemaster-config
                  key: FLAG_DB_NAME
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: togglemaster-config
                  key: FLAG_DB_USER
            - name: DB_SSLMODE
              valueFrom:
                configMapKeyRef:
                  name: togglemaster-config
                  key: DB_SSLMODE
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: flag-runtime-secrets
                  key: DB_PASSWORD
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: 75m
              memory: 96Mi
            limits:
              cpu: 300m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir:
            sizeLimit: 64Mi
