apiVersion: v1
kind: ConfigMap
metadata:
  name: togglemaster-config
data:
  AUTH_DB_HOST: __OCI_AUTH_DB_HOST__
  FLAG_DB_HOST: __OCI_FLAG_DB_HOST__
  TARGETING_DB_HOST: __OCI_TARGETING_DB_HOST__
  REDIS_URL: __OCI_REDIS_URL__
  OCI_REGION: __OCI_REGION__
  OCI_QUEUE_OCID: __OCI_QUEUE_OCID__
  OCI_QUEUE_MESSAGES_ENDPOINT: __OCI_QUEUE_MESSAGES_ENDPOINT__
  OCI_NOSQL_TABLE: __OCI_NOSQL_TABLE_OCID__
  OCI_COMPARTMENT_OCID: __OCI_COMPARTMENT_OCID__
  ANALYTICS_WORKER_ENABLED: "true"
