apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: togglemaster

resources:
  - ../../base
  - secret-provider-classes.yaml
  - database-init-jobs.yaml

configMapGenerator:
  - name: database-init
    files:
      - database/init.sh
      - database/auth.sql
      - database/flags.sql
      - database/targeting.sql

generatorOptions:
  disableNameSuffixHash: false

patches:
  - path: application-config-patch.yaml
  - path: auth-secret-mount-patch.yaml
  - path: flag-secret-mount-patch.yaml
  - path: targeting-secret-mount-patch.yaml
  - path: evaluation-secret-mount-patch.yaml

images:
  - name: togglemaster/auth-service
    newName: __OCIR_AUTH_SERVICE_IMAGE__
    newTag: __IMAGE_TAG__
  - name: togglemaster/flag-service
    newName: __OCIR_FLAG_SERVICE_IMAGE__
    newTag: __IMAGE_TAG__
  - name: togglemaster/targeting-service
    newName: __OCIR_TARGETING_SERVICE_IMAGE__
    newTag: __IMAGE_TAG__
  - name: togglemaster/evaluation-service
    newName: __OCIR_EVALUATION_SERVICE_IMAGE__
    newTag: __IMAGE_TAG__
  - name: togglemaster/analytics-service
    newName: __OCIR_ANALYTICS_SERVICE_IMAGE__
    newTag: __IMAGE_TAG__
