apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: auth-runtime-secrets
spec:
  provider: oci
  secretObjects:
    - secretName: auth-runtime-secrets
      type: Opaque
      data:
        - objectName: DB_PASSWORD
          key: DB_PASSWORD
        - objectName: MASTER_KEY
          key: MASTER_KEY
        - objectName: BOOTSTRAP_API_KEY
          key: BOOTSTRAP_API_KEY
  parameters:
    authType: workload
    vaultId: __OCI_VAULT_ID__
    secrets: |
      - name: __OCI_AUTH_APP_PASSWORD_SECRET_NAME__
        stage: CURRENT
        fileName: DB_PASSWORD
      - name: __OCI_AUTH_MASTER_KEY_SECRET_NAME__
        stage: CURRENT
        fileName: MASTER_KEY
      - name: __OCI_INTERNAL_API_KEY_SECRET_NAME__
        stage: CURRENT
        fileName: BOOTSTRAP_API_KEY
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: flag-runtime-secrets
spec:
  provider: oci
  secretObjects:
    - secretName: flag-runtime-secrets
      type: Opaque
      data:
        - objectName: DB_PASSWORD
          key: DB_PASSWORD
  parameters:
    authType: workload
    vaultId: __OCI_VAULT_ID__
    secrets: |
      - name: __OCI_FLAG_APP_PASSWORD_SECRET_NAME__
        stage: CURRENT
        fileName: DB_PASSWORD
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: targeting-runtime-secrets
spec:
  provider: oci
  secretObjects:
    - secretName: targeting-runtime-secrets
      type: Opaque
      data:
        - objectName: DB_PASSWORD
          key: DB_PASSWORD
  parameters:
    authType: workload
    vaultId: __OCI_VAULT_ID__
    secrets: |
      - name: __OCI_TARGETING_APP_PASSWORD_SECRET_NAME__
        stage: CURRENT
        fileName: DB_PASSWORD
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: evaluation-runtime-secrets
spec:
  provider: oci
  secretObjects:
    - secretName: evaluation-runtime-secrets
      type: Opaque
      data:
        - objectName: SERVICE_API_KEY
          key: SERVICE_API_KEY
  parameters:
    authType: workload
    vaultId: __OCI_VAULT_ID__
    secrets: |
      - name: __OCI_INTERNAL_API_KEY_SECRET_NAME__
        stage: CURRENT
        fileName: SERVICE_API_KEY
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: auth-database-init-secrets
spec:
  provider: oci
  parameters:
    authType: workload
    vaultId: __OCI_VAULT_ID__
    secrets: |
      - name: __OCI_AUTH_ADMIN_PASSWORD_SECRET_NAME__
        stage: CURRENT
        fileName: admin-password
      - name: __OCI_AUTH_APP_PASSWORD_SECRET_NAME__
        stage: CURRENT
        fileName: app-password
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: flag-database-init-secrets
spec:
  provider: oci
  parameters:
    authType: workload
    vaultId: __OCI_VAULT_ID__
    secrets: |
      - name: __OCI_FLAG_ADMIN_PASSWORD_SECRET_NAME__
        stage: CURRENT
        fileName: admin-password
      - name: __OCI_FLAG_APP_PASSWORD_SECRET_NAME__
        stage: CURRENT
        fileName: app-password
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: targeting-database-init-secrets
spec:
  provider: oci
  parameters:
    authType: workload
    vaultId: __OCI_VAULT_ID__
    secrets: |
      - name: __OCI_TARGETING_ADMIN_PASSWORD_SECRET_NAME__
        stage: CURRENT
        fileName: admin-password
      - name: __OCI_TARGETING_APP_PASSWORD_SECRET_NAME__
        stage: CURRENT
        fileName: app-password
