apiVersion: apps/v1
kind: Deployment
metadata:
  name: targeting-service
spec:
  template:
    spec:
      containers:
        - name: targeting-service
          volumeMounts:
            - name: secrets-store-inline
              mountPath: /mnt/secrets-store
              readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: targeting-runtime-secrets
