apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: togglemaster

resources:
  - namespaces/namespace.yaml
  - serviceaccounts.yaml
  - configmaps/application-config.yaml
  - deployments/auth-service.yaml
  - deployments/flag-service.yaml
  - deployments/targeting-service.yaml
  - deployments/evaluation-service.yaml
  - deployments/analytics-service.yaml
  - services/services.yaml
  - ingress/ingress.yaml
  - autoscaling/hpa.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: togglemaster
    includeSelectors: true
