apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flag-service
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: targeting-service
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: evaluation-service
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: analytics-service
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: database-init
automountServiceAccountToken: false
